// import "./src/styles/reset.css"
import "./src/styles/util.css"
import "./src/styles/global.css"
import "./src/styles/font-awesome.min.css"
import "./src/styles/form.css"
import "./node_modules/pretty-checkbox/src/pretty-checkbox.scss"
import "./node_modules/@mdi/font/scss/materialdesignicons.scss"
import "./src/styles/checkbox.scss"
